# Reference : https://github.com/mojombo/jekyll/wiki/Configuration

# site info
name         : Inject
version      : 0.6.0
logo         : /assets/images/logos/inject.png
stable_dl    : /download/0.6.x/inject-0.6.0.tgz
description  :
    short    : Dependency Management Got Awesome
    long     : CommonJS and AMD Compliant dependency loader for modern web apps

# documentation structure
documentation:
  - version: 0.6.x
    categories:
      - cat: cjs
        name: CommonJS Interface
      - cat: amd
        name: AMD Interface
      - cat: api
        name: The Inject API
      - cat: howto
        name: How To and Tutorials
  - version: 0.5.x
    old: true
    categories:
      - cat: cjs
        name: CommonJS Interface
      - cat: amd
        name: AMD Interface
      - cat: api
        name: The Inject API
      - cat: howto
        name: How To and Tutorials
  - version: 0.4.x
    old: true
    categories:
      - cat: api
        name: API
      - cat: howto
        name: How To

# permalinks
permalink : /:categories/:year/:month/:day/:title.html

# copyright notice
copyright :
  holder  : LinkedIn Corporation
  year    : 2012

# authors
authors :
  jheuser :
    name : Jakob Heuser
    li_pub_profile : https://www.linkedin.com/in/jakobheuser
    li_pic_url : http://m.c.lnkd.licdn.com/mpr/mpr/shrink_60_60/p/6/000/213/0ff/09a3f21.jpg
    github : Jakobo
    twitter : jakobo
  jhoff :
    name : Jordan Hoff
    li_pub_profile : https://www.linkedin.com/in/jordanhoff
    li_pic_url : https://m1-s.licdn.com/mpr/mpr/shrink_60_60/p/1/000/094/13f/3e7fa8b.jpg
    github : jhoff
    twitter : jhoff484
  mpowell :
    name : Matt Powell
    li_pub_profile: https://www.linkedin.com/in/mttpwll
    li_pic_url: https://m1-s.licdn.com/mpr/mpr/shrink_60_60/p/3/000/095/332/3c93849.jpg
    github: mattpowell
    twitter: mattpowell
  fsimeon :
    name : Fermin Simeon
    li_pub_profile: https://www.linkedin.com/in/ferminsimeon
    li_pic_url: http://m.c.lnkd.licdn.com/mpr/mpr/shrink_60_60/p/7/000/1ec/0d8/3840805.jpg
    github: fsimeon
    twitter: injectjs
  apmadhani :
    name : Akshay Madhani
    li_pub_profile: www.linkedin.com/pub/akshay-madhani/29/60/a59
    li_pic_url: http://m.c.lnkd.licdn.com/mpr/mpr/shrink_60_60/p/6/005/009/3d6/36b94f5.jpg
    github: apmadhani
    twitter: injectjs
  kmikles :
    name : Kevin Mikles
    li_pub_profile: https://www.linkedin.com/in/kevinmikles
    li_pic_url: http://m.c.lnkd.licdn.com/mpr/mpr/shrink_60_60/p/4/000/155/0ad/390a895.jpg
    github: gvsboy
    twitter: kevinfromwork

# publish posts with a future date
future    : true

# The production_url is only used when full-domain names are needed such as sitemap.txt
production_url : http://www.injectjs.com

# github defaults
lsi       : false
pygments  : true
safe      : false

# overrides maruku
markdown  : kramdown
kramdown  :
  entity_output : symbolic

# asset management
assets :
  cacheBurst : true
  stylesheets :
    - main
  vendor :
    scripts :
      jQuery :
        version : 1.8.2

# language
lang      : en

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
analytics :
  provider : google
  google :
    tracking_id : 'UA-1545927-5'

# Settings for Disqus
# Set 'shortname' to the disqus shortname
# Set 'developer' to 0 in production, 1 in development to view proper comments
disqus :
  shortname : injectjs
  developer : 0
